baseURL = "https://riversandinvestmentcompany.com/"
languageCode = "en-us"
title = "Rivers & Investment Company"
theme = "PaperMod"

[params]
  author = "Rivers & Investment Team"
  description = "Professional investment solutions for a modern world."
  ShowReadingTime = true
  ShowShareButtons = true
  defaultTheme = "dark"
